// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-0dG36CqaYmZD9B8rsQFvEc7H6H8DukY',
    appId: '1:467298360859:web:9673ca0ef0fe6e281b22be',
    messagingSenderId: '467298360859',
    projectId: 'wus-bike-blog',
    authDomain: 'wus-bike-blog.firebaseapp.com',
    storageBucket: 'wus-bike-blog.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmF0TwQYQPRNwJNlK9d2y8sjWlhEeOLWU',
    appId: '1:467298360859:android:a1834b27756add181b22be',
    messagingSenderId: '467298360859',
    projectId: 'wus-bike-blog',
    storageBucket: 'wus-bike-blog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNPJhl9VsYE4nKxPmxoM1xhDjkJXQEktk',
    appId: '1:467298360859:ios:08a78c9bba1d27c61b22be',
    messagingSenderId: '467298360859',
    projectId: 'wus-bike-blog',
    storageBucket: 'wus-bike-blog.appspot.com',
    iosClientId: '467298360859-sofcr974cqeub231js1amesddi45afp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNPJhl9VsYE4nKxPmxoM1xhDjkJXQEktk',
    appId: '1:467298360859:ios:be00ed4b36f105c41b22be',
    messagingSenderId: '467298360859',
    projectId: 'wus-bike-blog',
    storageBucket: 'wus-bike-blog.appspot.com',
    iosClientId: '467298360859-oj6rdv5kd8qf0pn8p7t9ceeo155o8i0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeBlog.RunnerTests',
  );
}
